gallows/lib/gallows_web/router.ex
defmodule GallowsWeb.Router do
  use GallowsWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :api do
    plug(:accepts, ["json"])
    plug(:fetch_session)
    plug(:put_secure_browser_headers)
  end

  scope "/api/hangman" do
    pipe_through(:api)

    post("/", GallowsWeb.Api.HangmanController, :create_game)
    put("/", GallowsWeb.Api.HangmanController, :make_guess)
  end

  scope "/hangman", GallowsWeb do
    # Use the default browser stack
    pipe_through(:browser)

    get("/", HangmanController, :new_game)
    post("/", HangmanController, :create_game)
    put("/", HangmanController, :make_guess)
  end

  # Other scopes may use custom stacks.
  # scope "/api", GallowsWeb do
  #   pipe_through :api
  # end
end

gallows/lib/gallows/application.ex
defmodule Gallows.Application do
  use Application

  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  def start(_type, _args) do
    import Supervisor.Spec

    # Define workers and child supervisors to be supervised
    children = [
      # Start the endpoint when the application starts
      supervisor(GallowsWeb.Endpoint, [])
      # Start your own worker by calling: Gallows.Worker.start_link(arg1, arg2, arg3)
      # worker(Gallows.Worker, [arg1, arg2, arg3]),
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Gallows.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    GallowsWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

gallows/lib/gallows_web/controllers/api/hangman_controller.ex
defmodule GallowsWeb.Api.HangmanController do
  use GallowsWeb, :controller
  @game_client Application.get_env(:gallows, :game_client)

  # POST
  # Create a new game
  def create_game(conn, _params) do
    game = Hangman.new_game()
    tally = Hangman.tally(game)

    json(conn, encode_to_json(%{game: game, tally: tally}))
  end

  PUT
  # Make a guess for a game
  def make_guess(conn, params = %{"guess" => %{"guess" => guess}}, opts \\ []) do
    game = get_session(conn, :game)

    case Hangman.make_move(game, guess) do
      {:error, msg} ->
        tally = Hangman.tally(game)
        json(conn, encode_to_json(%{error: msg, tally: tally}))

      tally ->
        json(conn, encode_to_json(%{tally: tally}))
    end
  end

  defp encode_to_json(val), do: Poison.encode!(val)
end

gallows/lib/gallows_web/controllers/hangman_controller.ex
defmodule GallowsWeb.HangmanController do
  use GallowsWeb, :controller

  def new_game(conn, _params) do
    render(conn, "new_game.html")
  end

  # POST
  # Create a new game
  def create_game(conn, _params) do
    game = Hangman.new_game()
    tally = Hangman.tally(game)

    put_session(conn, :game, game)
    |> render("game_field.html", tally: tally)
  end

  PUT
  # Make a guess for a game
  def make_guess(conn, params = %{"guess" => %{"guess" => guess}}) do
    game = get_session(conn, :game)

    case Hangman.make_move(game, guess) do
      {:error, msg} ->
        tally = Hangman.tally(game)

        conn
        |> put_flash(:error, msg)
        |> render("game_field.html", tally: tally)

      tally ->
        conn
        |> render("game_field.html", tally: tally)
    end
  end
end

gallows/lib/gallows_web/views/error_view.ex
defmodule GallowsWeb.ErrorView do
  use GallowsWeb, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render("500.html", assigns)
  end
end

gallows/lib/gallows_web/views/layout_view.ex
defmodule GallowsWeb.LayoutView do
  use GallowsWeb, :view
end

gallows/lib/gallows_web/templates/hangman/game_field.html.eex
<%= inspect(@tally) %>

<p>
  <%= get_flash(@conn, :error) %>
</p>

<p>
  Turns left: <%= @tally.turns_left %>
</p>

<p>
  Word so far: <%= word(@tally) %>
</p>

<p>
  <%= form_for @conn, hangman_path(@conn, :make_guess), [as: :guess, method: :put], fn(form) -> %>
    <%= text_input(form, :guess)%>
    <%= submit "Guess" %>
  <% end %>
</p>

gallows/lib/gallows_web/templates/hangman/new_game.html.eex
<h1>Welcome to Hangman</h1>



<p>
  <%= get_flash(@conn, :info) %>
</p>

<%= button("New game", to: hangman_path(@conn, :create_game)) %>

gallows/lib/gallows_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Gallows!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">

      <div id="test"></div>
      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>